---
- name: Using a REST API
  become: false
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Login to api
      uri:
        url: https://dev157152.service-now.com/api/now/table/sc_task?number=TASK0000001
        method: GET
        headers:
          Content-Type: application/json
        body_format: json
        status_code: 200
        user: admin
        password: r7OzdV%7Io*S
      register: response
    - debug:
        var: response
