- name: Using a REST API
  become: false
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Login to api
      uri:
        url: https://capeumsp.service-now.com
        method: GET
        headers:
          Content-Type: "application/json"
        body_format: json
        status_code: 200
        name: asr.engineer
        password: asr.engineer
      register: response
   
