- name: Using a REST API
  become: false
  hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: "api call"
- name: Login to api
  ansible.builtin.uri:
    url: https://capeumsp.service-now.com
    method: GET
    headers:
      Content-Type: "application/json"
    body_format: json
    status_code: 200
    name: asr.engineer
    password: asr.engineer
  register: response

